export const ERRORS = {
    ACCESS_DENIED: 'Access Denied',
    INPUT_EMPTY: 'Input empty',
    UNAUTHORIZED: 'UnAuthorized',
    USER_NOT_FOUND: "User not found",
    USER_EXIST: "User already exists",
    INVALID_USER_OR_EMAIL: "Invalid user or email",
    USER_ID_NOT_FOUND: 'User ID not found',
    USER_NOT_EXIST: "User does not exist",
    OLD_PASS_INCORRECT: "Old password is incorrect",
    TOKEN_INVALID: "Token is invalid",
    UPDATE_PASS_FAILED: "Update password failed",
    USER_INVALID: "Login name must be 4 to 18 characters in length and contains no special character",
    PASSWORD_INVALID: "Password is invalid",
    EMAIL_INVALID: "Email is invalid",
    USER_MISMATCH: "User mismatch",
    FROM_USER_NOT_FOUND: "From User not found",
    TO_USER_NOT_FOUND: "To User not found",
    EMAIL_TAKEN: "This email address is already taken",
    USERNAME_TAKEN: "Username is already taken",
    TYPE_REQUIRED: "Type required",
    TYPE_INVALID: "Type Invalid",
    FILE_NOT_FOUND: "File not found",
    RESET_TOKEN_INVALID: "Reset token is invalid",
    EMPLOYEE_CODE_IS_EXISTED: "Employee code is already existing",

    // Staff Management
    STAFF_ID_INVALID: "The list staff ID is invalid or incorrect",
    STAFF_ID_NOT_FOUND: "Staff ID not found",
    DELETE_STAFF_FAILS: "Delete staff failed",
    STATUS_INVALID_OR_WRONG: "Status is invalid or wrong",
    MEDREP_ID_INVALID: "Medrep ID is invalid",
    MEDREP_NOT_FOUND: "Medrep not found",
    USER_NOT_FOUND_OR_WRONG_ROLE: "User cannot be found or incorrect role",
    STAFF_NOT_FOUND: "Staff not found",

    TYPES_INVALID: "Types invalid",
    PHONE_NUMBER_INVALID: "Phone number is invalid",
    INVALID_PHONE_NUMBER_OR_PASSWORD: "Invalid phone number or password",
    YOU_HAVE_NOT_LOGIN_YET: "You're not logged in yet",
    USERNAME_INVALID: "Username is invalid",


    USER_ID_INVALID: "User ID is invalid",
    YOU_HAVE_QUIT: "You have quit",

    ACCOUNT_ID_INVALID: "Account ID is invalid",
    TYPE_USER_INVALID: "Type user is invalid",
    ACCESS_TOKEN_INVALID: "Access token is invalid",
    ACCOUNT_IS_BLOCKED: "This account is blocked",
    LOGIN_LIMIT_EXCEEDED: "Login limit has been exceeded",
    FORGET_LIMIT_EXCEEDED: "Forget password has been exceeded",

    USERNAME_PASSWORD_NOT_CORRECT: 'Invalid username or password',
    ACCOUNT_NOT_VERIFY: `Account is not verify`,
    SALT_NOT_CORRECT: `Sale not correct`,
    EMPLOYEE_CODE_NOT_CORRECT: `Employee code is incorrect`,
    USERNAME_OR_PASSWORD_IS_INCORRECT: "Invalid username or password",

    ID_INVALID: 'Invalid ID',
    ID_NOT_FOUND: 'ID not found',
    EMAIL_REQUIRED: 'Email is required',

    CODE_REQUIRED: 'Code is required',
    CODE_VERIFY_INVALID: 'Code verify is invalid',

    PASSWORD_WRONG_FORMAT: 'Password must be 6 to 18 characters in length',
    PASSWORD_NOT_MATCH: 'Password not match',
    EMAIL_WRONG_FORMAT: 'The email is not in the correct format.',
    EMAIL_EXIST: 'This email already exists.',
    NODE_CREATE_ADDRESS: 'Node create address',
    STATUS_INVALID: 'Status is invalid',

    PERMISSON_NOT_FOUND: "Permission not found",
    SET_ROLE_DENIED: "Set role denied",
    ROLE_NOT_FOUND: "Role not found",
    ROLE_ID_INVALID: "Role ID is invalid",

    MEMBER_NOT_FOUND: "Member not found",
    TYPE_MEMBER_INVALID: "Type member is invalid",

    SOCKET_IS_NOT_CONNECTED: "Socket is not connect",

    SLUG_INVALID: "Slug is invalid",
    FORMAT_DOCUMENT_ERROR: "Document is not in the correct format (docx, dotx, pdf, potx, xls, xlsx, zip, rar)", // - use docx,dotx,pdf,potx,xls,xlsx,zip,rar
    FILE_LARGER_THAN_100MB: "File must be larger than 100MB",
    TITLE_LARGER_THAN_50: "The title larger than 50",

    FORMAT_VIDEO_ERROR: "Video is not in the correct format (avi, flv, wmv, mp4, mov)",
    FILE_LARGER_THAN_200MB: "File must be larger than 200MB",

    CLONE_ALREADY_EXIST: "Clone already exists",

    INVALID_UPLOAD_FILE: 'Invalid upload file',
    FORMAT_AUDIO_ERROR: 'Format audio error',
    FORMAT_IMAGE_ERROR: 'Format image error',

    BOOKING_NOT_FOUND: "Booking not found",
    EMPLOYEE_EXIT: "Employee already exists",
    EMPLOYEE_NOT_FOUND: "Employee not found",
    CUSTOMER_EXIT: "Customer already exists",
    CUSTOMER_NOT_FOUND: "Customer not found",
    SERVICE_ERROR: "Service error",
    PHONE_EXIST: "Phone number already exists",
    PHONE_ALREADY_EXISTS: "Phone number already exists",
    TIME_ERROR: "Time error",
    RANK_NOT_FOUND: "Rank not found",
    AREASOFCONCERN_NOT_FOUND: "Area of concern not found",
    WORK_NOT_FOUND: "Work not found",
    KOL_NOT_RANK: "KOL not found",
    KOL_NOT_FOUND: "KOL not found",
    WALLET_NOT_FOUND: 'Wallet not found',
    NOT_ENOUGH_MONEY: 'Not enough money',
    APPLY_EXISTING_WORK: 'Apply existing work',
    APPLY_WORK_NOT_FOUND: 'Apply work not found',
    MONEY_IS_NOT_ENOUGH: 'Not enough money',
    REQUEST_CANCELLATION_NOT_FOUND: 'The request cancellation not found',
    RATE_ALREADY_EXISTS: 'Rate already exists',
    SOLUTION_INVALID: 'Invalid solution',
    FAULT_BY_INVALID: 'Fault by is invalid',
    WORK_ID_INVALID: 'Invalid Work ID',
    CANCELER_ID_INVALID: 'Canceler ID is invalid',
    WORK_STATUS_INVALID: 'Invalid Work Status',
    AMOUNT_INVALID: 'Invalid amount',
    WITHDRAW_NOT_FOUND: 'Withdraw not found',
    SETTING_NOT_FOUND: 'Setting not found',
    PASSWORD_WRONG: 'Wrong password',
    INBOX_NOT_FOUND: 'Inbox not found',
    CODE_NOT_FOUND: 'Code not found',
    START_DATE_INVALID: 'Start date is invalid',
    NOTIFICATION_WORK_NOT_FOUND: 'Notification work not found',
    EMAIL_IS_NOT_VERIFIED: 'Email have not verified yet',
    POST_NOT_FOUND: 'Post not found',
    PAYMENT_NOT_FOUND: 'Payment not found',
    STORE_NOT_FOUND: 'Store not found',

    STORE_NUMBER_INVALID: "Invalid Store number",
    PIN_CODE_INVALID: "Invalid PIN code",
    STORE_NUMBER_OR_PIN_CODE_IS_NOT_CORRECT: "The store number or PIN code is incorrect",
    STORE_IS_DEACTIVE: "The store is inactive",

    CODE_INVALID: "Invalid Code",
    OTP_NOT_FOUND: "OTP not found",
    CODE_IS_INCORRECT: "Code is not correct",
    CODE_IS_USED: "Code is used",
    CODE_EXPIRED: "Code is expired",

    ACTIVE_CODE_INVALID: "Active Code is invalid",
    ACTIVE_CODE_OR_STORE_NUMBER_IS_INCORRECT: "Active code or Store number is incorrect",
    STORE_ID_INVALID: "Invalid Store ID",
    STORE_NUMBER_IS_INCORRECT: "Store number is incorrect",

    NAME_INVALID: "Invalid Name",
    BARCODE_INVALID: "Invalid Barcode",
    PRICE_INVALID: "Invalid Price",
    QUANTITY_INVALID: "Invalid Quantity",
    PRODUCT_NAME_IS_EXISTED: "Product name already exists",
    BARCODE_IS_EXISTED: "Barcode already exists",
    CATEGORY_ID_INVALID: "Invalid Category ID",
    CATEGORY_NOT_FOUND: "Category not found",
    PRODUCT_ID_INVALID: "Product ID is invalid",
    PRODUCT_NOT_FOUND: "Product not found",

    CATEGORY_NAME_INVALID: "Category name is invalid",
    CATEGORY_NAME_IS_EXISTED: "Category name already exists",

    DURATION_INVALID: "Invalid duration",
    DEPOSIT_AMOUNT_INVALID: "Invalid deposit amount",
    SERVICE_NAME_IS_EXISTED: "Service name already exists",
    SERVICE_ID_INVALID: "Invalid service ID",
    SERVICE_NOT_FOUND: "Service not found",

    END_DATE_INVALID: "Invalid end date",
    START_DATE_NOT_GREATER_THAN_END_DATE: "Start date is not greater than End date",
    CODE_IS_EXISTED: "Code already exists",
    PROMOTION_ID_INVALID: "Promotion ID is invalid",
    PROMOTION_NOT_FOUND: "Promotion not found",

    BOOKING_ID_INVALID: "Booking ID is invalid",
    DEPOSIT_PAYMENT_INVALID: "Invalid deposit payment",
    POS_AMOUNT_INVALID: "POS amount is invalid",
    LAST_4_INVALID: "Invalid Last 4",
    REF_NO_INVALID: "Invalid Ref No",
    RECEIPT_PICTURE_INVALID: "Receipt picture is invalid",
    PAYMENT_INVALID: "Invalid payment",
    PROMOTION_DATE_INVALID: "Promotion date is invalid",
    YOU_USED_THIS_PROMOTION: "You used this promotion",
    SERVICE_APPLIED_PROMOTION_NOT_FOUND: "Service applied promotion not found",
    PAYMENT_AMOUNT_INVALID: "Payment amount is invalid",
    BOOKING_NO_INVALID: "Invalid Booking No",

    PIN_CODE_NOT_FOUND: "PIN code not found",
    PIN_CODE_ALREADY_EXISTS: "PIN code already exists",
    DONT_SEND_EMAIL: `Don't send email`,

    GENDER_INVALID: "Invalid gender",
    MONTH_INVALID: "Invalid month",
    SUBJECT_INVALID: "Invalid subject",
    CONTENT_INVALID: "Invalid content",
    DISCOUNT_INVALID: "Invalid discount",
    FROM_DATE_INVALID: "From date is invalid",
    TO_DATE_INVALID: "To date is invalid",
    START_TIME_INVALID: "Star time is invalid",
    END_TIME_INVALID: "End time is invalid",
    PROMOTION_INVALID: "Invalid Promotion",
    THIS_BOOKING_IS_ALREADY_CHECKED_OUT: "This booking is already checked out",
    CUSTOMER_USED_THIS_PROMOTION: "Customer used this promotion",

    BIRTH_MONTH_INVALID: "Birthdate month is invalid",
};
